app:
    resource: '@AppBundle/Controller/'
    type: annotation

#lucky/number:
#    resource: '@AppBundle/Controller/LuckyController::numberAction'
#    type: annotation

#/nuevo/producto:
#    resource: '@AppBundle/Controller/FormController::newProductAction'
#    type: annotation