<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByName($value)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT *
                FROM AppBundle:Product p
                WHERE p.name = :name 
                ORDER BY p.name ASC')
            ->setParameter('name',$value)
            ->getResult();
    }
}
